### ISSUE TITLE
v1.1.1 identified as containing a coin 

### ISSUE THREAD

**Issue by SR7122** [tronscan/tronscan-desktop#19]
I downloaded v1.1.1 last night at home. Kaspersky did not like it and kept deleting it. Kaspersky thought that it contained a coin trojan. I noticed that the zip size was 62 MB. Today I downloaded it at work, Kaspersky liked it, and noticed the zip size was 53 MB.

What is going on?

**Comment by Rovak** [comment]
I've tried some different build methods and replaced the version after getting the same report from other users. There are a lot of false positive detection's going on. This seems to be quite common for Electron applications because of some of the API's it uses. 

* https://github.com/electron/electron/issues/4485
* https://github.com/electron/electron-quick-start/issues/154

I always check the versions before uploading and it didn't report any. I double checked the executable right after the release after someone reported a false positive (https://www.virustotal.com/nl/file/51eca96df8ea483076e9b52739eb8480823ae8e335eca51a1fc841370765016d/analysis/1532084728/). But i can't exclude the possibility that a virus dodged the radar or that somehow the version got replaced with a virus through a leaked API key.

**Comment by SR7122** [comment]
Thanks. I was thinking maybe someone hacked into GitHub and replaced the zip. The 1.1.1 zip I downloaded yesterday was 64MB. That one was flagged by Kaspersky. The 1.1.1 I downloaded today was 54MB. I still have the zip if you want it.

 

Todd
