### ISSUE TITLE
Problem with ledger nano s and tronscan to withdraw funds

### ISSUE THREAD

**Issue by gloginjar** [tronscan/tronscan-desktop#35]
Hello. I received my ledger nano s and i set it to work with tron.I was able to receiver coin from a exchange but now i can not send.When trying to send them,it asks for confirmation from the device, i confirm from the ledger nano s but i get the following message:. "Something went wrong while submitting the transaction". Could you help me?. thank you
Forgive you for a bad English spelling!
![tron greska](https://user-images.githubusercontent.com/7263386/46626396-87fdd800-cb37-11e8-99cc-4f30dd0f104f.jpg)

**Comment by Anukshuk** [comment]
I have the same problem. Very frustrating to say the least. I do not even get conformation from the device.

**Comment by jaypal123** [comment]
I just got it. Try leaving atleast 1 trx behind. Worked this time

**Comment by jakubsn** [comment]
it usually help top quit Tronscan and start it again -  I hope they will address this issue though as it is quite annoying

**Comment by Anukshuk** [comment]
Thanks. I did the same by quitting the app and restarting it again.

**Comment by lbjenious** [comment]
About "something went wrong while submitting the transaction"
I too am having the sam problem but have been unable to get to a root cause. I seems that the NANO S Ledger gets stuck in some loop.

send via 
1. confirm send
2. confirm trx address
3. confirm amount

A few times the transaction did complete although the error message display "something went wrong while submitting the transaction"... only after repeating the 1-2-3 sequence many, many times.

FYI: The error message/pattern described previously seemed to have started approximately around Q3-Q4 2018.... Previously, it only required one click to confirm Ledger Nano S SEND TRX amount per transaction; to succeed.

IS ANYONE ELSE HAVING THIS PROBLEM?

 Ledger NANO S and TRONSCAN Desktop Client definitely not syncing like before...

FYI: I also have tried the Blockchain (dex) Explorer but I can't even open the wallet. I did make sure though Ledger Nano S is set to Browser mode vs Client Application when using TRON.

**Comment by davidjhk** [comment]
You don't have to use Tron Wallet Desktop for Legder Wallet. 
Ledger website has a new guide to use Tron Wallet on Ledger Wallet. 
Here is the link: https://support.ledger.com/hc/en-us/articles/360006904193-TRON-TRX- 
I was able to send out TRX successfully with this method.
Still TRC10 tokens could not be sent out with the same error, but TRX withdrawal works well.
I hope this may help.

**Comment by benjo1717** [comment]
Hi, i m trying to send TRC10 from my tronscan account with my ledger nano S but i still get the following message: "Something went wrong while submitting the transaction".

Could you help me?
thank

**Comment by davidjhk** [comment]
Recently I found another way to send out ERC10 tokens from Ledger Nano S. TronWatchMarket has released its final desktop wallet beta on January 12. Here is the link:
https://github.com/TronWatch/Desktop-Wallet/releases/tag/Beta-v1.0.13
Although I was able to transfer tokens from Ledger Nano S, it is marked to be deprecated. So I decided to transfer out all the tokens from Ledger Nano S until I find stable solution. I hope this will help.
