### ISSUE TITLE
 I do not see the wallet address!!

### ISSUE THREAD

**Issue by mattia24** [tronscan/tronscan-desktop#49]
I have turned on with ledger nano s and I do not see the address of the wallet tron ​​to receive the TRX.
How do I solve the problem ??

**Comment by Bwest981** [comment]
I am having the same problem. First time using it. Not sure whats going on.

**Comment by GarethTRelph** [comment]
I also cannot see the wallet address. I have support emails telling me to uninstall and re-install, check firmware releases etc. but the problem still exists.

**Comment by GarethTRelph** [comment]
I have tweeted Justin Sun and the problem still exists

**Comment by fomman** [comment]
hey guys, its been fixed already....a long time ago
Here is the link: https://tronscan.github.io/tronscan-frontend/#/
Plus, let you know that you can use TronWach app as well, it does support Ledger since yesterday.
P.s all apps available on Mac

**Comment by GarethTRelph** [comment]
Thankyou for the update. I hope all the new users are getting access to the
correct working version.

**Comment by JanosT1704** [comment]
Just to add some more information that are true for me but must not be for others still more info is always better:

1.) The issue is not fixed in the downloadable app, atleast not in the Windows version (neither 1.1.0 nor 1.1.1).
2.) Opening the wallet with the web-app only works when using Chrome.
